kind: BuildConfig
apiVersion: v1
metadata:
  name: demo-rest-rollback-pipeline
spec:
  source:
    git:
      uri: https://github.com/dsanchor/demo-cicd
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: pipeline/Jenkinsfile-rollback
      env:
        - name: CICD_GIT_URL
          value: https://github.com/dsanchor/demo-cicd
        - name: APP_NAME
          value: demo-rest
        - name: IMAGESTREAM_PROJECT
          value: development
        - name: TEST_PROJECT
          value: test
        - name: PROD_PROJECT
          value: production
        - name: POSTMAN_TESTS_COLLECTION
          value: "https://raw.githubusercontent.com/dsanchor/demo-rest/master/openshift/tests/demo-rest.postman_collection.json"
        - name: POSTMAN_TEST_ENVIRONMENT_CONFIG
          value: "https://raw.githubusercontent.com/dsanchor/demo-rest/master/openshift/tests/environments/test.postman_environment.json"
        - name: POSTMAN_PROD_ENVIRONMENT_CONFIG
          value: "https://raw.githubusercontent.com/dsanchor/demo-rest/master/openshift/tests/environments/production.postman_environment.json"
